import { Ionicons } from "@expo/vector-icons";
import * as LocalAuthentication from "expo-local-authentication";
import { router } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, useColorScheme, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { GlassCard } from "@/components/ui";
import { GASTIFY_THEMES, type GastifyColorScheme } from "@/constants/theme";
import { ApiError, authenticatedFetch, type ApiUser } from "@/services/api";
import { createAppPin, getBiometricsEnabled, hasAppPin, setBiometricsEnabled } from "@/services/appLock";
import { useAuth } from "@/store/AuthProvider";

export default function ProfileScreen() {
    const scheme: GastifyColorScheme = useColorScheme() === "dark" ? "dark" : "light";
    const theme = GASTIFY_THEMES[scheme];
    const { signOut } = useAuth();
    const [user, setUser] = useState<ApiUser | null>(null);
    const [loading, setLoading] = useState(true);
    const [biometrics, setBiometrics] = useState(false);
    const [hasPin, setHasPin] = useState(false);
    const [pin, setPin] = useState("");
    const [confirmPin, setConfirmPin] = useState("");
    useEffect(() => { void (async () => { try { const [response, enabled, pinExists] = await Promise.all([authenticatedFetch("/api/v1/auth/me"), getBiometricsEnabled(), hasAppPin()]); if (!response.ok) throw new ApiError("Unable to load profile.", response.status); setUser(await response.json() as ApiUser); setBiometrics(enabled); setHasPin(pinExists); } finally { setLoading(false); } })(); }, []);
    const savePin = async () => { if (!/^\d{4,6}$/.test(pin)) { Alert.alert("Invalid PIN", "Use a 4 to 6 digit PIN."); return; } if (pin !== confirmPin) { Alert.alert("PINs do not match", "Enter the same PIN twice."); return; } await createAppPin(pin); setPin(""); setConfirmPin(""); setHasPin(true); Alert.alert("PIN created", "Your app will lock when reopened."); };
    const toggleBiometrics = async (enabled: boolean) => { if (!hasPin && enabled) { Alert.alert("Create a PIN first", "A PIN is required as a fallback unlock method."); return; } if (enabled) { const available = await LocalAuthentication.hasHardwareAsync() && await LocalAuthentication.isEnrolledAsync(); if (!available) { Alert.alert("Biometrics unavailable", "Set up Face ID or fingerprint on this device first."); return; } const result = await LocalAuthentication.authenticateAsync({ promptMessage: "Enable Gastify biometric lock" }); if (!result.success) return; } setBiometrics(enabled); await setBiometricsEnabled(enabled); };
    const logout = async () => { await signOut(); router.replace("/(onboarding)"); };
    return <SafeAreaView style={[styles.safeArea, { backgroundColor: theme.background }]}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={[styles.eyebrow, { color: theme.textMuted }]}>ACCOUNT</Text><Text style={[styles.title, { color: theme.textPrimary }]}>Profile</Text>{loading ? <ActivityIndicator style={styles.loader} color={theme.textPrimary} /> : <><GlassCard contentStyle={styles.userCard} tintColor={theme.glassTint}><View style={[styles.avatar, { backgroundColor: theme.brandSurface }]}><Ionicons color={theme.icon} name="person-outline" size={30} /></View><Text style={[styles.name, { color: theme.textPrimary }]}>{user?.username ?? "Gastify user"}</Text><Text style={[styles.email, { color: theme.textSecondary }]}>{user?.email ?? ""}</Text></GlassCard><Text style={[styles.section, { color: theme.textMuted }]}>SETTINGS</Text>{!hasPin ? <GlassCard contentStyle={styles.pinCard} tintColor={theme.glassTint}><Text style={[styles.settingTitle, { color: theme.textPrimary }]}>Create PIN</Text><Text style={[styles.settingText, { color: theme.textSecondary }]}>Use this PIN when opening Gastify again.</Text><TextInput keyboardType="number-pad" maxLength={6} onChangeText={setPin} placeholder="Create 4–6 digit PIN" placeholderTextColor={theme.textMuted} secureTextEntry style={[styles.pinInput, { color: theme.textPrimary, borderColor: theme.brandBorder }]} value={pin}/><TextInput keyboardType="number-pad" maxLength={6} onChangeText={setConfirmPin} placeholder="Confirm PIN" placeholderTextColor={theme.textMuted} secureTextEntry style={[styles.pinInput, { color: theme.textPrimary, borderColor: theme.brandBorder }]} value={confirmPin}/><Pressable onPress={() => void savePin()} style={[styles.pinButton, { backgroundColor: theme.primaryButton }]}><Text style={[styles.pinButtonText, { color: theme.primaryButtonText }]}>Create PIN</Text></Pressable></GlassCard> : null}<GlassCard contentStyle={styles.setting} tintColor={theme.glassTint}><View style={styles.settingCopy}><Text style={[styles.settingTitle, { color: theme.textPrimary }]}>Biometric lock</Text><Text style={[styles.settingText, { color: theme.textSecondary }]}>Use Face ID or fingerprint to unlock Gastify.</Text></View><Switch onValueChange={(value) => void toggleBiometrics(value)} trackColor={{ false: theme.paginationInactive, true: theme.textPrimary }} value={biometrics} /></GlassCard><Pressable onPress={() => void logout()} style={styles.logout}><Ionicons color="#DC2626" name="log-out-outline" size={21} /><Text style={styles.logoutText}>Log out</Text></Pressable></>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safeArea: { flex: 1 }, content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 17, paddingBottom: 112 }, eyebrow: { fontSize: 11, fontWeight: "800", letterSpacing: 1.6 }, title: { marginTop: 5, fontSize: 29, fontWeight: "800", letterSpacing: -0.8 }, loader: { marginTop: 80 }, userCard: { marginTop: 24, padding: 24, alignItems: "center" }, avatar: { width: 68, height: 68, borderRadius: 34, alignItems: "center", justifyContent: "center" }, name: { marginTop: 13, fontSize: 19, fontWeight: "800" }, email: { marginTop: 4, fontSize: 13 }, section: { marginTop: 28, marginBottom: 9, marginLeft: 4, fontSize: 11, fontWeight: "800", letterSpacing: 1.2 }, setting: { padding: 18, flexDirection: "row", alignItems: "center", gap: 14 }, settingCopy: { flex: 1 }, settingTitle: { fontSize: 15, fontWeight: "800" }, settingText: { marginTop: 4, fontSize: 12, lineHeight: 17 }, pinCard: { padding: 18, gap: 10 }, pinInput: { minHeight: 48, borderWidth: StyleSheet.hairlineWidth, borderRadius: 14, paddingHorizontal: 14, fontSize: 15 }, pinButton: { minHeight: 48, borderRadius: 15, alignItems: "center", justifyContent: "center" }, pinButtonText: { fontSize: 14, fontWeight: "800" }, logout: { marginTop: "auto", marginBottom: 20, minHeight: 54, borderRadius: 18, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, backgroundColor: "rgba(220,38,38,0.10)" }, logoutText: { color: "#DC2626", fontSize: 14, fontWeight: "800" } });
